### ISSUE TITLE
iOS: Screen rotation in split view leads to errors in GUI Layout

### ISSUE THREAD

**Issue by kebekus** [Akaflieg-Freiburg/addhoursandminutes#5]
The title says it all… open the app in split view mode, then rotate the display by 90 degrees. The app recognized the rotation and switches to a garbled layout. Rotating back does not resolve the issue.

**Comment by schneisi** [comment]
A first analysis indicates that we need an other way to calculate the safe area. Currently, we base it on the screen height and width, but obviously, that doesn't work in split mode.

With that in mind, it's clear why this behavior occurs on a 9.7" iPad. On my 12.9" iPad, this only occurs after rotating the device. It's currently unclear to me why.

Nevertheless, we need a new way to calculate the safe margins.

**Comment by kebekus** [comment]
@schneisi I understand what you write, but I am not fully convinced yet. A look that the screen suggests to me that the window width/height is correct in split view mode and after rotation but that the app does not switch between the "portrait" and "landscape" layout modes.

I have opened a new branch splitRotation, where we might do a few experiments.

- In the file "Calculator.qml", I have replaced the function "isPortrait()" with a standard property binding and added some debug output. In retrospect, I do not understand why "isPortrait()" was a function in the first place -- maybe I didn't understand what property bindings were when I wrote that.

@schneisi Could you please try out the branch splitRotation:

- Does the new code already solve the issue?
- If no, what does a look at the debug output say? When we rotate the device with/without split view, does the app re-evalutate the property isPortrait?

Besten Danke, und bis demnächst,

Stefan.

**Comment by schneisi** [comment]
Thanks Stefan, but unfortunately, I could not observe an improved behaviour.

I don't think the switch between Landscape and Portrait is the reason.
Side View has a little sister called [Slide Over](https://support.apple.com/en-us/HT207582). In that mode, the app itself should always stay it portrait mode, due to its small width.
After initiating Slide Over, the apps look good and the following is being logged:
`[qml] Portrait Mode 375 712`

After rotation, the layout breaks. It logs
`[qml] Portrait Mode 320 1072`
The logging is as expected

I added logging code for the dimensions of the primary screen, on which we base the calculation of the safe margins.
`Primary Screen: 1180 748`
This was logged while in Slide Over.

The hardware resolution is 2360 x 1640, which is (almost) half of the logged height and the width.
Therefore the primaryScreen dimensions represent the total display, not just the part that is available to the app.

I think this supports the theory that we cannot use the primary screen dimensions.

I also have an explanation on why it only happens after the rotation:
on an iPad, the safe margins are zero.
Entering Side View does not trigger the update Method - it is only triggered by the orientation change. So the safe margins stay at zero and the layout is correct.
Rotating the device triggers the update. The safe margins are now being calculated based on the primary screen ⇒ we have a garbled layout.

**Comment by kebekus** [comment]
@schneisi Ok, you win. I guess we need platform-specific code then?

**Comment by schneisi** [comment]
I think I've got a working solutions. A quick test with the Simulator looks promising. Will test more thoroughly and clean up the code this weekend.

**Comment by schneisi** [comment]
Looks good on a real device too. I merged your branch into ios and I will deploy a new version via TestFlight today.

**Comment by kebekus** [comment]
Very well! I will then close this issue now. Thanks for all the work.
